services:
  # Recursive DNS Resolver
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    restart: unless-stopped
    hostname: unbound
    volumes:
      - ./etc-unbound:/opt/unbound/etc/unbound/
    networks:
      privacy_net:
        ipv4_address: 10.10.10.2
    # Log Rotation Policy: Prevent disk saturation
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # DNS Sinkhole and Ad-blocker
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    depends_on:
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    cap_add:
      - SYS_TIME
      - SYS_NICE
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
      - PIHOLE_DNS_=${PIHOLE_DNS_IP}#53
      - DNSSEC=true
      - DNSMASQ_LISTENING=all
      - MAXDBDAYS=90 # Database retention limit (3 months)
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      privacy_net:
        ipv4_address: 10.10.10.3
    # Log Rotation Policy: Prevent disk saturation
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  privacy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24